package pojos;
// Generated Dec 22, 2019 10:32:27 AM by Hibernate Tools 4.3.1



/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private String courseCode;
     private String courseName;
     private int credit;
     private String category;
     private int level;

    public Course() {
    }

    public Course(String courseCode, String courseName, int credit, String category, int level) {
       this.courseCode = courseCode;
       this.courseName = courseName;
       this.credit = credit;
       this.category = category;
       this.level = level;
    }
   
    public String getCourseCode() {
        return this.courseCode;
    }
    
    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode;
    }
    public String getCourseName() {
        return this.courseName;
    }
    
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }
    public int getCredit() {
        return this.credit;
    }
    
    public void setCredit(int credit) {
        this.credit = credit;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public int getLevel() {
        return this.level;
    }
    
    public void setLevel(int level) {
        this.level = level;
    }




}


