package pojos;
// Generated Dec 22, 2019 10:32:27 AM by Hibernate Tools 4.3.1



/**
 * Gpaformula generated by hbm2java
 */
public class Gpaformula  implements java.io.Serializable {


     private Integer id;
     private int programmeId;
     private int credit;

    public Gpaformula() {
    }

    public Gpaformula(int programmeId, int credit) {
       this.programmeId = programmeId;
       this.credit = credit;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getProgrammeId() {
        return this.programmeId;
    }
    
    public void setProgrammeId(int programmeId) {
        this.programmeId = programmeId;
    }
    public int getCredit() {
        return this.credit;
    }
    
    public void setCredit(int credit) {
        this.credit = credit;
    }




}


