package pojos;
// Generated Dec 22, 2019 10:32:27 AM by Hibernate Tools 4.3.1



/**
 * Marks generated by hbm2java
 */
public class Marks  implements java.io.Serializable {


     private Integer id;
     private String grade;
     private int gpv;

    public Marks() {
    }

    public Marks(String grade, int gpv) {
       this.grade = grade;
       this.gpv = gpv;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }
    public int getGpv() {
        return this.gpv;
    }
    
    public void setGpv(int gpv) {
        this.gpv = gpv;
    }




}


