package pojos;
// Generated Dec 22, 2019 10:32:27 AM by Hibernate Tools 4.3.1



/**
 * ProgrammeCourse generated by hbm2java
 */
public class ProgrammeCourse  implements java.io.Serializable {


     private Integer pcId;
     private int programmeId;
     private String courseCode;
     private String courseType;
     private String taketoGpa;

    public ProgrammeCourse() {
    }

    public ProgrammeCourse(int programmeId, String courseCode, String courseType, String taketoGpa) {
       this.programmeId = programmeId;
       this.courseCode = courseCode;
       this.courseType = courseType;
       this.taketoGpa = taketoGpa;
    }
   
    public Integer getPcId() {
        return this.pcId;
    }
    
    public void setPcId(Integer pcId) {
        this.pcId = pcId;
    }
    public int getProgrammeId() {
        return this.programmeId;
    }
    
    public void setProgrammeId(int programmeId) {
        this.programmeId = programmeId;
    }
    public String getCourseCode() {
        return this.courseCode;
    }
    
    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode;
    }
    public String getCourseType() {
        return this.courseType;
    }
    
    public void setCourseType(String courseType) {
        this.courseType = courseType;
    }
    public String getTaketoGpa() {
        return this.taketoGpa;
    }
    
    public void setTaketoGpa(String taketoGpa) {
        this.taketoGpa = taketoGpa;
    }




}


