package pojos;
// Generated Dec 22, 2019 10:32:27 AM by Hibernate Tools 4.3.1



/**
 * Programme generated by hbm2java
 */
public class Programme  implements java.io.Serializable {


     private Integer programmeId;
     private String programmeName;
     private String specialisation;
     private String curriculum;

    public Programme() {
    }

    public Programme(String programmeName, String specialisation, String curriculum) {
       this.programmeName = programmeName;
       this.specialisation = specialisation;
       this.curriculum = curriculum;
    }
   
    public Integer getProgrammeId() {
        return this.programmeId;
    }
    
    public void setProgrammeId(Integer programmeId) {
        this.programmeId = programmeId;
    }
    public String getProgrammeName() {
        return this.programmeName;
    }
    
    public void setProgrammeName(String programmeName) {
        this.programmeName = programmeName;
    }
    public String getSpecialisation() {
        return this.specialisation;
    }
    
    public void setSpecialisation(String specialisation) {
        this.specialisation = specialisation;
    }
    public String getCurriculum() {
        return this.curriculum;
    }
    
    public void setCurriculum(String curriculum) {
        this.curriculum = curriculum;
    }




}


