package pojos;
// Generated Dec 22, 2019 10:32:27 AM by Hibernate Tools 4.3.1



/**
 * StudentCourse generated by hbm2java
 */
public class StudentCourse  implements java.io.Serializable {


     private Integer id;
     private int regNo;
     private String courseCode;
     private String mark;

    public StudentCourse() {
    }

    public StudentCourse(int regNo, String courseCode, String mark) {
       this.regNo = regNo;
       this.courseCode = courseCode;
       this.mark = mark;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getRegNo() {
        return this.regNo;
    }
    
    public void setRegNo(int regNo) {
        this.regNo = regNo;
    }
    public String getCourseCode() {
        return this.courseCode;
    }
    
    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode;
    }
    public String getMark() {
        return this.mark;
    }
    
    public void setMark(String mark) {
        this.mark = mark;
    }




}


